using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AccionMovimiento : MonoBehaviour
{
    public GameObject mo単ecoParent;
    public Transform[] array;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    void OnMouseDown()
    {
        mo単ecoParent.GetComponent<Moverse>().setDir(1);
        GetComponent<CircleCollider2D>().enabled = true;
        GetComponent<CircleCollider2D>().radius = mo単ecoParent.GetComponent<Moverse>().rangoMovimiento*30.6f;
        mo単ecoParent.GetComponent<Moverse>().setMenu(false);
        
    }
}
